### PR TITLE
sign up and sign in properly working

### PR DESCRIPTION
**Pull request by michaellauu**
finally.

### CODE REVIEW

**Comment by anthonydevelops** [comment]
Also, I just realized this pull is 12 commits behind master, so we can't merge this until it's updated & those errors are fixed as well.

**Comment by michaellauu** [comment]
its actually fine to be 12 commits behind master because I didnt implement any changes to the files you touched since then (you can view the changes between commits). As for the fs/path I can remove that.

**Comment by michaellauu** [comment]
I also brought over the commits just in case.

**Comment by anthonydevelops** [comment]
I'm pretty sure you always want the latest changes, that way you're not creating merge conflicts or deleting previously written code in the repo. For instance, you did modify serverjs, and I did see the changes and that's why mentioned the conflicting JSON and URL parsers. Glad you fixed it though!

**Pull request merged**
